### ISSUE TITLE
Can't resolve `./objectives_pb.js`

### ISSUE THREAD

**Issue by metalmatze** [bufbuild/connect-web#236]
**Describe the bug**

`buf.gen.yaml`
```
version: v1
plugins:
  - name: go
    out: proto
    opt: paths=source_relative
  - name: connect-go
    out: proto
    opt: paths=source_relative
  - name: es
    path: ui/node_modules/.bin/protoc-gen-es
    out: ui/src/proto
    opt: target=ts
  - name: connect-web
    path: ui/node_modules/.bin/protoc-gen-connect-web
    out: ui/src/proto
    opt: target=ts
```

Produces the correct TypeScript files. It's just that that the `ui/src/proto/objectives/v1alpha1/objectives_connectweb.ts` links to the files next to it `ui/src/proto/objectives/v1alpha1/objectives_pb.ts` with the following line:
```
import {GetObjectiveStatusRequest, GetObjectiveStatusResponse, ListObjectivesRequest, ListObjectivesResponse} from "./objectives_pb.js";
```

This breaks with:
```
Failed to compile.

Module not found: Error: Can't resolve './objectives_pb.js' in '/home/metalmatze/src/github.com/pyrra-dev/pyrra/ui/src/proto/objectives/v1alpha1'
ERROR in ./src/proto/objectives/v1alpha1/objectives_connectweb.ts 9:0-138
Module not found: Error: Can't resolve './objectives_pb.js' in '/home/metalmatze/src/github.com/pyrra-dev/pyrra/ui/src/proto/objectives/v1alpha1'

webpack compiled with 1 error
```

Right now it's easy to fix by deleting the `.js` suffix from the import in `objectives_connectweb.ts`.
However, this has to be done after every single `buf generate`...

**To Reproduce**

If you encountered an error message, please copy and paste it verbatim.
If the bug is specific to an RPC or payload, please provide a reduced
example.

**Environment (please complete the following information):**
- @bufbuild/connect-web version: `0.1.0`
- Framework and version: `react@18.1.0`
- Browser and version: Brave Version 1.42.97

I'll post the PR to my open-source project, once it's up.
