### ISSUE TITLE
buf generate fails on windows with 'node_modules' is not recognized...

### ISSUE THREAD

**Issue by alexandros-megas** [bufbuild/connect-web#244]
**Describe the bug**

I'm trying to follow the instructions on [connect.build](https://connect.build/docs/web/generating-code) to build my company's protos into a TS grpc client for use in browser (not nodeJS).

When I run `buf generate` I get the following error message:

```
> buf generate
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
Failure: plugin es: exit status 1; exit status 1; exit status 1; exit status 1; exit status 1; exit status 1; exit status 1; exit status 1
```

**To Reproduce**

buf.yaml
```
version: v1
deps:
  - buf.build/googleapis/googleapis
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

buf.gen.yaml
```
version: v1
plugins:
  - name: es
    path: node_modules/.bin/protoc-gen-es
    out: dist
    opt: target=ts
  - name: connect-web
    path: node_modules/.bin/protoc-gen-connect-web
    out: dist
    opt: target=ts
```

buf.lock
```
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 80720a488c9a414bb8d4a9f811084989
```

With the above setup, I open git bash (I tried it in powershell as well, with the same results), run `buf generate` and get the error message I see above at the top of the ticket.

**Environment (please complete the following information):**
```
    "@bufbuild/connect-web": "^0.1.0",
    "@bufbuild/protobuf": "^0.1.0"
    "@bufbuild/protoc-gen-connect-web": "^0.1.0",
    "@bufbuild/protoc-gen-es": "^0.1.0",
```

node version `v16.13.1`
yarn version `1.22.18`
npm version `8.1.2`

**Additional context**
Can confirm I have the expected executables in my `node_modules` dir

<img width="844" alt="image" src="https://user-images.githubusercontent.com/55400979/187011434-6f159ac1-bdd8-4ce6-a197-33e0b5586513.png">
