### ISSUE TITLE
how to generate code for dependent protos   ?  e.g., google types:  date/datetime 

### ISSUE THREAD

**Issue by xmlking** [bufbuild/connect-web#262]
Is there a way to generate TS code when I use `import "google/type/datetime.proto";`  dependency?

Repo for reproduction: https://github.com/xmlking/entity-resolution

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/627951/188790788-b9e994a2-f914-4165-8754-5b80718667f1.png">

Proto File :https://github.com/xmlking/entity-resolution/blob/main/proto/entityapis/er/schema/entity/v1/entity.proto 
Generated TS file: https://github.com/xmlking/entity-resolution/blob/main/gen/ts/er/schema/entity/v1/entity_pb.ts#L8-L10

Other TS plugins have options `generate_dependencies` to generate code for google types
```
  - remote: buf.build/timostamm/plugins/protobuf-ts:v2.4.0-1
    out: gen/ts
    opt:
      - generate_dependencies
      - ts_nocheck
      - eslint_disable
```

<img width="329" alt="image" src="https://user-images.githubusercontent.com/627951/188791334-88660fbe-a497-4d34-a04c-20e572e6e687.png">
