### ISSUE TITLE
[Question] How to access the endpoints defined in gRPC-Gateway google.api.http with the generated TypeScript code.

### ISSUE THREAD

**Issue by AtaruOhto** [bufbuild/connect-web#293]
I'm a newbie who has recently started using bufbuild/connect-web.
I think it's a great tool and we want to generate TypeScript client code with it. 

We want to access HTTP endpoints defined in `google.api.http`.
But endpoints defined with  gRPC-Gateway `google.api.http`  is not included in generated TypeScript client codes.
Is there any way to access endpoints defined in gRPC-Gateway with generated clients?

```
# our proto file.

service DeviceService {
  rpc GetDevices(GetDevicesRequest) returns (GetDevicesResponse) {

    // this endpoint defined by google.api.http won't be included in the generated TypeScript client codes.
    // We want to access the endpoint below with generated TypeScript client codes.

    option (google.api.http) = {
      get: "/api/v5/devices"
    };
  }
}

```

```
# buf.gen.ts.yaml

version: v1
plugins:
  - name: es
    path: node_modules/.bin/protoc-gen-es
    out: connect_web_gen
    opt: target=ts
  - name: connect-web
    path: node_modules/.bin/protoc-gen-connect-web
    out: connect_web_gen
    opt: target=ts
```

```
# generated TypeScript codes.

/**
 * @generated from service service.app.device.v5.DeviceService
 */
export const DeviceService = {
  typeName: "service.app.device.v5.DeviceService",
  methods: {
    /**
     * @generated from rpc service.app.device.v5.DeviceService.GetDevices
     */
    getDevices: {
      name: "GetDevices",
      I: GetDevicesRequest,
      O: GetDevicesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
```

http://localhost:4010/service.app.device.v5.DeviceService/GetDevices
But we want to access http://localhost:4010/api/v5/devices with the code below

```
...

const client = createPromiseClient(
  DeviceService,
  createConnectTransport({
    baseUrl: 'http://localhost:4010/',
  }),
)
...
```

Could you tell me how to access the defined http endpoints in `google.api.http` with the code generated TypeScript code?
If you need additional information, please let me know.

Thank you in advance.
